### ISSUE TITLE
importerror

### ISSUE THREAD

**Issue by shadowhcy** [luanshiyinyang/FacialExpressionRecognition#16]
ImportError: cannot import name 'UI' from 'ui' (D:\PycharmProjects\FacialExpressionRecognition-master\venv\lib\site-packages\ui\__init__.py)

**Comment by luanshiyinyang** [comment]
please set environment like my [blog](https://zhouchen.blog.csdn.net/article/details/94584047), we recommend you to use conda.

**Comment by yichangjianduan** [comment]
> ImportError: cannot import name 'UI' from 'ui' (D:\PycharmProjects\FacialExpressionRecognition-master\venv\lib\site-packages\ui__init__.py)

我也是 请问你解决了吗
